### ISSUE TITLE
 [PlatformIO registry] I can't find the library using PlatformIO registry search

### ISSUE THREAD

**Issue by hpsaturn** [paulvha/SN-GCJA5#1]
## Summary

Hi, maybe the library was not published yet? because I don't found it via `pio` search tools (web and via CLI)

For example:

```bash
pio pkg search GCJA5

Found 2 packages (page 1 of 1)

sparkfun/SparkFun Particle Sensor Panasonic SN-GCJA5
Library • 1.0.1 • Published on Mon Sep 21 20:19:21 2020
A library to communicate with the Panasonic SN-GCJA5 particle sensor. Communicates with the SN-GCJA5 over I<sup>2</sup>C to quickly integrate a particle sensor into your project. The sensor detects particulate mass density and particle count for various size particles from PM1.0 to PM10 (0.3-10um). The sensor requires 5V supply and 3.3V I<sup>2</sup>C.

hpsaturn/CanAirIO Air Quality Sensors Library
Library • 0.5.8 • Published on Fri Aug 26 21:56:53 2022
Generic sensor manager, abstratctions and bindings of multiple air sensors libraries: Honeywell, Plantower, Panasonic, Sensirion, Nova, etc. and CO2 sensors. Also it handling others environment sensors. This library is for general purpose but also is the sensors library base of CanAirIO project.

```

**Comment by paulvha** [comment]
hi

I have not created nor tested nor published it for platformIO as I have no plans to do that. 

kind regards,
Paul

**Comment by hpsaturn** [comment]
Thanks for your fast response. Well, we can use the library with specific commit, but we could lost possible new versions. And also for continuous integration pipe this change could improve the tests in projects that using the library. On the other hand the registry of PlatformIO is a good alternative to have more feedback or code contributions in your library. I don't know, maybe you should keep in mind it.

**Comment by paulvha** [comment]
Actually, I was not impressed at all with this sensor (also see the .ODT in the extras folder. I have not done any work on it for the last 2 years. So you are welcome if you want to post the library as it is :-)

**Comment by hpsaturn** [comment]
Well I can do it, a pull request to your repo with PlatformIO manifest and I'll there like a maintainer. I have never done that in the past, but I could try this.

Regarding of the Panasonic Sensor, well, I think that it is a good alternative to Sensirion SPS30. For example the noise reduction is better than Sensirion. And some times the GCJA5 is more cheaper. Some users in CanAirIO project use this sensor, for this reason we have support for it with your library.

Thanks for your feedback.

**Comment by paulvha** [comment]
Good luck. !
